#                                    PROGRAM-1
                                   Arrays and Metrices

# Name- KANHAIYA KUMAR
Roll No- CSC/20/13

University Roll No- 20059570011

# (A):Create arrays with specific values:

In [6]:
import numpy as np

In [7]:
import pandas as pd

In [9]:
#(i) array of all ones
a1=np.ones(6)

In [10]:
a1

array([1., 1., 1., 1., 1., 1.])

In [11]:
#(ii) array of all zeros
a2= np.zeros(6)

In [12]:
a2

array([0., 0., 0., 0., 0., 0.])

In [13]:
#(iii) array with random values within a range
a3 = np.random.randint(4,20,8)

In [14]:
a3

array([ 9, 12, 12, 11, 12, 14, 10, 17])

In [15]:
#(iv) a diagonal matrix
diagonal = np.eye(4)

In [16]:
diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# (B) Perform other matrix operations:

In [17]:
arr1 = np.array([-1.2,2.0,3.4,-4,5,6.8,-8,9.9,-0.1]).reshape(3,3)

In [18]:

arr1

array([[-1.2,  2. ,  3.4],
       [-4. ,  5. ,  6.8],
       [-8. ,  9.9, -0.1]])

In [19]:
#(i) convert matrix data to absolute values
M1=np.absolute(arr1)

In [20]:
M1

array([[1.2, 2. , 3.4],
       [4. , 5. , 6.8],
       [8. , 9.9, 0.1]])

In [21]:
#(i) convert matrix data to negative values
M2 = np.negative(arr1)

In [22]:
M2

array([[ 1.2, -2. , -3.4],
       [ 4. , -5. , -6.8],
       [ 8. , -9.9,  0.1]])

In [23]:
#(iii) add rows & columns from a matrix
M3 = np.append(arr1, M2, axis = 0)

In [24]:
M3

array([[-1.2,  2. ,  3.4],
       [-4. ,  5. ,  6.8],
       [-8. ,  9.9, -0.1],
       [ 1.2, -2. , -3.4],
       [ 4. , -5. , -6.8],
       [ 8. , -9.9,  0.1]])

In [25]:
#(iv) remove rows & columns from a matrix
   # delete 1 st row
data = np.delete(M3, 1, 0)
print("data  after 1 st  row deleted :", data)

data  after 1 st  row deleted : [[-1.2  2.   3.4]
 [-8.   9.9 -0.1]
 [ 1.2 -2.  -3.4]
 [ 4.  -5.  -6.8]
 [ 8.  -9.9  0.1]]


In [26]:
   # delete 0 th column
data = np.delete(M3, 0, 1)
print("data  after 0 th  column  deleted :", data)

data  after 0 th  column  deleted : [[ 2.   3.4]
 [ 5.   6.8]
 [ 9.9 -0.1]
 [-2.  -3.4]
 [-5.  -6.8]
 [-9.9  0.1]]


In [27]:
#(v) find the maximum and  minimum values in a matrix or in a row/colum
M2

array([[ 1.2, -2. , -3.4],
       [ 4. , -5. , -6.8],
       [ 8. , -9.9,  0.1]])

In [38]:
 #(v) find the maximum and  minimum values in a matrix or in a row/column
M2.max() #Maimum value

8.0

In [40]:
M2.min() #Minimum value

-9.9

In [42]:
 #(vi) find the sum of some/all elements in a matrix
total=np.sum(M2)
total


-13.8