# PROGRAM-2
                            File Handling

# Name- KANHAIYA KUMAR
Roll NO- CSC/20/13

University Roll No- 20059570011

In [52]:
import numpy as np

In [53]:
import pandas as pd

# (A)Load data from a text file (file should contain matrix data)

In [54]:

# Text file data converted to integer data type
File_data = np.loadtxt("f2.txt", dtype=int)
print(File_data)

[[18 13 15]
 [ 2  6 15]
 [17  2  9]]








# (B)Use commands to compute the:

In [55]:
#(i)Size of matrix
len(File_data)

3

In [56]:
#(ii) size/length of a particular row/column

In [57]:
#Size of 1st columns
len(File_data[:,1])

3

In [58]:
#Size of Zeroth Row
len(File_data[0])

3

# (C)  store matrix data to a text file

In [59]:
d1=np.random.randint(1,20,9).reshape(3,3)
d1

array([[10, 16, 18],
       [ 5, 15,  3],
       [11,  9, 19]])

In [60]:
np.savetxt("f2c.txt", d1)
 

In [61]:
content = np.loadtxt('f2c.txt')
print("\nContent in file1.txt:\n", content)


Content in file1.txt:
 [[10. 16. 18.]
 [ 5. 15.  3.]
 [11.  9. 19.]]
