# PROGRM-3
                                        Matrices

# Name- KANHAIYA KUMAR
Roll no- CSC/20/13

University Roll No- 20059570011


# (A) Perform basic operation on matrices

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [11]:
M1 = np.random.randint(2,20,9).reshape(3,3)

In [12]:
M2 = np.random.randint(1,10,9).reshape(3,3)

In [13]:
M1

array([[ 3, 10,  5],
       [10, 17, 17],
       [19,  3, 13]])

In [14]:
M2

array([[9, 9, 7],
       [5, 7, 4],
       [3, 3, 7]])

In [15]:
#(i) addition of 2 matrices
M3=M1+M2

In [16]:
M3

array([[12, 19, 12],
       [15, 24, 21],
       [22,  6, 20]])

In [17]:
#(ii) subtraction of 2 matrices
M4=M1-M2

In [18]:
M4

array([[-6,  1, -2],
       [ 5, 10, 13],
       [16,  0,  6]])

In [19]:
#(iii) Multiplication of 2 matrices
M5=M1*M2

In [20]:
M5

array([[ 27,  90,  35],
       [ 50, 119,  68],
       [ 57,   9,  91]])

In [27]:
#(iv) Transpose of  matrices
M6=np.transpose(M5)

In [28]:
M6

array([[ 27,  50,  57],
       [ 90, 119,   9],
       [ 35,  68,  91]])

# (B)Display specific rows or column of matrix

In [31]:
M7 = np.random.randint(2,100,36).reshape(6,6)

In [32]:
M7

array([[91, 34, 63, 22, 92, 39],
       [24, 65, 97, 26, 69, 49],
       [89, 52, 47, 58, 18, 44],
       [65, 92, 93, 15, 54, 78],
       [85, 19,  4, 55,  5,  3],
       [92, 90, 54,  2, 67, 95]])

In [35]:
#Specific rows and columns
print(M7[0:2,1:5])

[[34 63 22 92]
 [65 97 26 69]]
